export const INCREMENT_PAGE = 'INCREMENT_PAGE';
export const FETCH_PHOTOS_REQUEST = 'FETCH_PHOTOS_REQUEST';
export const FETCH_PHOTOS_FAILURE = 'FETCH_PHOTOS_FAILURE';
export const FETCH_PHOTOS_SUCCESS = 'FETCH_PHOTOS_SUCCESS';
export const DETAIL_PHOTO = 'DETAIL_PHOTO';
export const LOAD_FIRST_IMAGE = 'LOAD_FIRST_IMAGE';
